# Generated by Django 5.0.2 on 2024-03-02 04:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpl_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('ALL_ROUNDER', 'All Rouder'), ('BOWLER', 'Bowler'), ('BATSMAN', 'Batsman'), ('WICKET_KEEPER', 'Wicket Keeper'), ('WICKET_KEEPER_BATSMAN', 'Wicket Keeper Batsman'), ('OTHERS', 'Others')], max_length=100)),
                ('card', models.FileField(upload_to='players/card')),
                ('photo', models.FileField(upload_to='players/photo')),
                ('basic_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_icon', models.BooleanField()),
                ('is_sold', models.BooleanField()),
                ('created_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'players',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpl_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('logo', models.FileField(upload_to='teams/logo')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expended_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'teams',
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateField(auto_now=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cpl_backend.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cpl_backend.team')),
            ],
            options={
                'db_table': 'bids',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now=True)),
                ('players', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cpl_backend.player')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cpl_backend.team')),
            ],
            options={
                'db_table': 'team_players',
            },
        ),
    ]
