# Generated by Django 5.0.2 on 2024-03-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpl_backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='card',
            field=models.FileField(blank=True, null=True, upload_to='players/card'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='players/photo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='balance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
