# Generated by Django 5.0.2 on 2024-03-02 05:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpl_backend', '0002_alter_player_card_alter_player_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='is_sold',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
