# Generated by Django 5.0.2 on 2024-03-02 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpl_backend', '0003_bid_is_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='is_icon',
            new_name='is_external',
        ),
        migrations.AlterField(
            model_name='player',
            name='basic_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='team',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=20000, max_digits=10),
        ),
    ]
