# Generated by Django 5.0.2 on 2024-03-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpl_backend', '0004_rename_is_icon_player_is_external_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='card',
            field=models.FileField(blank=True, null=True, upload_to='media/players/card'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='media/players/photo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.FileField(upload_to='media/teams/logo'),
        ),
    ]
