# Generated by Django 5.0.2 on 2024-03-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpl_backend', '0005_alter_player_card_alter_player_photo_alter_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bid_amount',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='card',
            field=models.FileField(blank=True, null=True, upload_to='players/card'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='players/photo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.FileField(upload_to='teams/logo'),
        ),
        migrations.AlterField(
            model_name='team',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=40000, max_digits=10),
        ),
    ]
